# Generated by Django 4.2.4 on 2023-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('article_text', models.CharField(max_length=500)),
                ('photos', models.ImageField(upload_to='article_photos/')),
                ('location', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
